# Generated by Django 4.2.7 on 2023-11-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mommyblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiitle',
            new_name='title',
        ),
    ]
